/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cn.siat.dex.server;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum DexAppType implements org.apache.thrift.TEnum {
  WC(1),
  DTR(2),
  DTC(3),
  PGRANK(4),
  KMEANS(5);

  private final int value;

  private DexAppType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static DexAppType findByValue(int value) { 
    switch (value) {
      case 1:
        return WC;
      case 2:
        return DTR;
      case 3:
        return DTC;
      case 4:
        return PGRANK;
      case 5:
        return KMEANS;
      default:
        return null;
    }
  }
}
