/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cn.siat.dex.server;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum DexResStatus implements org.apache.thrift.TEnum {
  EXCEPTION(1),
  SMALLRES(2),
  LARGERES(3);

  private final int value;

  private DexResStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static DexResStatus findByValue(int value) { 
    switch (value) {
      case 1:
        return EXCEPTION;
      case 2:
        return SMALLRES;
      case 3:
        return LARGERES;
      default:
        return null;
    }
  }
}
