/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cn.siat.dex.server;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-01-13")
public class LargeRes implements org.apache.thrift.TBase<LargeRes, LargeRes._Fields>, java.io.Serializable, Cloneable, Comparable<LargeRes> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("LargeRes");

  private static final org.apache.thrift.protocol.TField RES_DEX_FIELD_DESC = new org.apache.thrift.protocol.TField("resDex", org.apache.thrift.protocol.TType.STRUCT, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new LargeResStandardSchemeFactory());
    schemes.put(TupleScheme.class, new LargeResTupleSchemeFactory());
  }

  public DexResDes resDex; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    RES_DEX((short)1, "resDex");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RES_DEX
          return RES_DEX;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RES_DEX, new org.apache.thrift.meta_data.FieldMetaData("resDex", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT        , "DexResDes")));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(LargeRes.class, metaDataMap);
  }

  public LargeRes() {
  }

  public LargeRes(
    DexResDes resDex)
  {
    this();
    this.resDex = resDex;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public LargeRes(LargeRes other) {
    if (other.isSetResDex()) {
      this.resDex = other.resDex;
    }
  }

  public LargeRes deepCopy() {
    return new LargeRes(this);
  }

  @Override
  public void clear() {
    this.resDex = null;
  }

  public DexResDes getResDex() {
    return this.resDex;
  }

  public LargeRes setResDex(DexResDes resDex) {
    this.resDex = resDex;
    return this;
  }

  public void unsetResDex() {
    this.resDex = null;
  }

  /** Returns true if field resDex is set (has been assigned a value) and false otherwise */
  public boolean isSetResDex() {
    return this.resDex != null;
  }

  public void setResDexIsSet(boolean value) {
    if (!value) {
      this.resDex = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case RES_DEX:
      if (value == null) {
        unsetResDex();
      } else {
        setResDex((DexResDes)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case RES_DEX:
      return getResDex();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case RES_DEX:
      return isSetResDex();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof LargeRes)
      return this.equals((LargeRes)that);
    return false;
  }

  public boolean equals(LargeRes that) {
    if (that == null)
      return false;

    boolean this_present_resDex = true && this.isSetResDex();
    boolean that_present_resDex = true && that.isSetResDex();
    if (this_present_resDex || that_present_resDex) {
      if (!(this_present_resDex && that_present_resDex))
        return false;
      if (!this.resDex.equals(that.resDex))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_resDex = true && (isSetResDex());
    list.add(present_resDex);
    if (present_resDex)
      list.add(resDex);

    return list.hashCode();
  }

  @Override
  public int compareTo(LargeRes other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetResDex()).compareTo(other.isSetResDex());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResDex()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.resDex, other.resDex);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("LargeRes(");
    boolean first = true;

    sb.append("resDex:");
    if (this.resDex == null) {
      sb.append("null");
    } else {
      sb.append(this.resDex);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class LargeResStandardSchemeFactory implements SchemeFactory {
    public LargeResStandardScheme getScheme() {
      return new LargeResStandardScheme();
    }
  }

  private static class LargeResStandardScheme extends StandardScheme<LargeRes> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, LargeRes struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RES_DEX
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.resDex = new DexResDes();
              struct.resDex.read(iprot);
              struct.setResDexIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, LargeRes struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.resDex != null) {
        oprot.writeFieldBegin(RES_DEX_FIELD_DESC);
        struct.resDex.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class LargeResTupleSchemeFactory implements SchemeFactory {
    public LargeResTupleScheme getScheme() {
      return new LargeResTupleScheme();
    }
  }

  private static class LargeResTupleScheme extends TupleScheme<LargeRes> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, LargeRes struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetResDex()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetResDex()) {
        struct.resDex.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, LargeRes struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.resDex = new DexResDes();
        struct.resDex.read(iprot);
        struct.setResDexIsSet(true);
      }
    }
  }

}

