/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cn.siat.dex.server;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
public class SmallRes extends org.apache.thrift.TUnion<SmallRes, SmallRes._Fields> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SmallRes");
  private static final org.apache.thrift.protocol.TField WC_RES_FIELD_DESC = new org.apache.thrift.protocol.TField("wcRes", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField DTC_RES_FIELD_DESC = new org.apache.thrift.protocol.TField("dtcRes", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField DTR_RES_FIELD_DESC = new org.apache.thrift.protocol.TField("dtrRes", org.apache.thrift.protocol.TType.STRUCT, (short)3);

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    WC_RES((short)1, "wcRes"),
    DTC_RES((short)2, "dtcRes"),
    DTR_RES((short)3, "dtrRes");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // WC_RES
          return WC_RES;
        case 2: // DTC_RES
          return DTC_RES;
        case 3: // DTR_RES
          return DTR_RES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.WC_RES, new org.apache.thrift.meta_data.FieldMetaData("wcRes", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT        , "WCRes")));
    tmpMap.put(_Fields.DTC_RES, new org.apache.thrift.meta_data.FieldMetaData("dtcRes", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT        , "DTCRes")));
    tmpMap.put(_Fields.DTR_RES, new org.apache.thrift.meta_data.FieldMetaData("dtrRes", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT        , "DTRRes")));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SmallRes.class, metaDataMap);
  }

  public SmallRes() {
    super();
  }

  public SmallRes(_Fields setField, Object value) {
    super(setField, value);
  }

  public SmallRes(SmallRes other) {
    super(other);
  }
  public SmallRes deepCopy() {
    return new SmallRes(this);
  }

  public static SmallRes wcRes(WCRes value) {
    SmallRes x = new SmallRes();
    x.setWcRes(value);
    return x;
  }

  public static SmallRes dtcRes(DTCRes value) {
    SmallRes x = new SmallRes();
    x.setDtcRes(value);
    return x;
  }

  public static SmallRes dtrRes(DTRRes value) {
    SmallRes x = new SmallRes();
    x.setDtrRes(value);
    return x;
  }


  @Override
  protected void checkType(_Fields setField, Object value) throws ClassCastException {
    switch (setField) {
      case WC_RES:
        if (value instanceof WCRes) {
          break;
        }
        throw new ClassCastException("Was expecting value of type WCRes for field 'wcRes', but got " + value.getClass().getSimpleName());
      case DTC_RES:
        if (value instanceof DTCRes) {
          break;
        }
        throw new ClassCastException("Was expecting value of type DTCRes for field 'dtcRes', but got " + value.getClass().getSimpleName());
      case DTR_RES:
        if (value instanceof DTRRes) {
          break;
        }
        throw new ClassCastException("Was expecting value of type DTRRes for field 'dtrRes', but got " + value.getClass().getSimpleName());
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected Object standardSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TField field) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(field.id);
    if (setField != null) {
      switch (setField) {
        case WC_RES:
          if (field.type == WC_RES_FIELD_DESC.type) {
            WCRes wcRes;
            wcRes = new WCRes();
            wcRes.read(iprot);
            return wcRes;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case DTC_RES:
          if (field.type == DTC_RES_FIELD_DESC.type) {
            DTCRes dtcRes;
            dtcRes = new DTCRes();
            dtcRes.read(iprot);
            return dtcRes;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case DTR_RES:
          if (field.type == DTR_RES_FIELD_DESC.type) {
            DTRRes dtrRes;
            dtrRes = new DTRRes();
            dtrRes.read(iprot);
            return dtrRes;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      return null;
    }
  }

  @Override
  protected void standardSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case WC_RES:
        WCRes wcRes = (WCRes)value_;
        wcRes.write(oprot);
        return;
      case DTC_RES:
        DTCRes dtcRes = (DTCRes)value_;
        dtcRes.write(oprot);
        return;
      case DTR_RES:
        DTRRes dtrRes = (DTRRes)value_;
        dtrRes.write(oprot);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected Object tupleSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, short fieldID) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(fieldID);
    if (setField != null) {
      switch (setField) {
        case WC_RES:
          WCRes wcRes;
          wcRes = new WCRes();
          wcRes.read(iprot);
          return wcRes;
        case DTC_RES:
          DTCRes dtcRes;
          dtcRes = new DTCRes();
          dtcRes.read(iprot);
          return dtcRes;
        case DTR_RES:
          DTRRes dtrRes;
          dtrRes = new DTRRes();
          dtrRes.read(iprot);
          return dtrRes;
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      throw new TProtocolException("Couldn't find a field with field id " + fieldID);
    }
  }

  @Override
  protected void tupleSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case WC_RES:
        WCRes wcRes = (WCRes)value_;
        wcRes.write(oprot);
        return;
      case DTC_RES:
        DTCRes dtcRes = (DTCRes)value_;
        dtcRes.write(oprot);
        return;
      case DTR_RES:
        DTRRes dtrRes = (DTRRes)value_;
        dtrRes.write(oprot);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TField getFieldDesc(_Fields setField) {
    switch (setField) {
      case WC_RES:
        return WC_RES_FIELD_DESC;
      case DTC_RES:
        return DTC_RES_FIELD_DESC;
      case DTR_RES:
        return DTR_RES_FIELD_DESC;
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TStruct getStructDesc() {
    return STRUCT_DESC;
  }

  @Override
  protected _Fields enumForId(short id) {
    return _Fields.findByThriftIdOrThrow(id);
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  public WCRes getWcRes() {
    if (getSetField() == _Fields.WC_RES) {
      return (WCRes)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'wcRes' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setWcRes(WCRes value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.WC_RES;
    value_ = value;
  }

  public DTCRes getDtcRes() {
    if (getSetField() == _Fields.DTC_RES) {
      return (DTCRes)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'dtcRes' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setDtcRes(DTCRes value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.DTC_RES;
    value_ = value;
  }

  public DTRRes getDtrRes() {
    if (getSetField() == _Fields.DTR_RES) {
      return (DTRRes)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'dtrRes' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setDtrRes(DTRRes value) {
    if (value == null) throw new NullPointerException();
    setField_ = _Fields.DTR_RES;
    value_ = value;
  }

  public boolean isSetWcRes() {
    return setField_ == _Fields.WC_RES;
  }


  public boolean isSetDtcRes() {
    return setField_ == _Fields.DTC_RES;
  }


  public boolean isSetDtrRes() {
    return setField_ == _Fields.DTR_RES;
  }


  public boolean equals(Object other) {
    if (other instanceof SmallRes) {
      return equals((SmallRes)other);
    } else {
      return false;
    }
  }

  public boolean equals(SmallRes other) {
    return other != null && getSetField() == other.getSetField() && getFieldValue().equals(other.getFieldValue());
  }

  @Override
  public int compareTo(SmallRes other) {
    int lastComparison = org.apache.thrift.TBaseHelper.compareTo(getSetField(), other.getSetField());
    if (lastComparison == 0) {
      return org.apache.thrift.TBaseHelper.compareTo(getFieldValue(), other.getFieldValue());
    }
    return lastComparison;
  }


  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();
    list.add(this.getClass().getName());
    org.apache.thrift.TFieldIdEnum setField = getSetField();
    if (setField != null) {
      list.add(setField.getThriftFieldId());
      Object value = getFieldValue();
      if (value instanceof org.apache.thrift.TEnum) {
        list.add(((org.apache.thrift.TEnum)getFieldValue()).getValue());
      } else {
        list.add(value);
      }
    }
    return list.hashCode();
  }
  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


}
